version: 2

models:
  - name: fct_sales
    description: "Fato de vendas, com receita e margem por item"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: revenue
        description: "Receita total do item"
      - name: profit
        description: "Lucro total do item"

  - name: dim_products
    description: "Catálogo de produtos com dados de precificação"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: margin
        description: "Margem unitária"

  - name: dim_customer
    description: "Clientes com dados de comportamento de churn"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: total_orders
      - name: is_churn
        tests:
          - accepted_values:
              values: [0, 1]
